// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zfnvgurtzidnzijkijuw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmbnZndXJ0emlkbnppamtpanV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MjE3NzIsImV4cCI6MjA2MjI5Nzc3Mn0.6u9-ZTO9-h3GK9TNFD6FLTp6pBbnal-7jR2Y3kWoFec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);